### ISSUE TITLE
Add support for nexus 5

### ISSUE THREAD

**Issue by zbraniecki** [eliperelman/node-mozdevice#17]
It would help to have nexus 5 support in config.json (also, a more meaningful error when raptor is launched against an unknown device type ;))

**Comment by zbraniecki** [comment]
I tried to add it manually, 

Added:
      "hammerhead": {
        "hdmiResolution": "720p",
        "inputEvent": "/dev/input/event0",
        "dimensions": [1080, 1920],
        "swipePadding": [40, 40, 40, 40]
      },

to config.json and modified mozdevice.setConfiguration to use hammerhead as a model.

Unfortunately, it still doesn't work, this time with:

zbraniecki@zbmbp:~/projects/gaia (master %>)$ APP=settings node tests/raptor/launch_test
[Raptor] Preparing to start testing...
[Cold Launch: Settings] Suite aborted due to error
[Raptor] Testing complete
[Raptor] Error summary:

Error: Test timeout exceeded 60000ms
    at Phase.timeoutError (/Volumes/projects/gaia/node_modules/gaia-raptor/lib/suite/phase.js:70:22)
    at null._onTimeout (/Volumes/projects/gaia/node_modules/gaia-raptor/lib/suite/phase.js:92:12)
    at Timer.listOnTimeout (timers.js:110:15)

Not sure why it times out, but I suspect that gaia-raptor also cannot recognize the device.
